# Generated by Django 5.2.8 on 2025-11-11 09:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='条码')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='型号')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='位置')),
                ('scanner', models.CharField(blank=True, max_length=100, null=True, verbose_name='扫描人员')),
                ('scan_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '条码汇总',
                'verbose_name_plural': '条码汇总',
                'db_table': 'asset_code_barcode_summary',
            },
        ),
    ]
