# Generated by Django 5.2.8 on 2025-11-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodesummary',
            name='actual_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际处理时间'),
        ),
        migrations.AddField(
            model_name='barcodesummary',
            name='asset_type',
            field=models.CharField(blank=True, default='研发样机', max_length=100, null=True, verbose_name='资产类型'),
        ),
        migrations.AddField(
            model_name='barcodesummary',
            name='expected_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预计处理时间'),
        ),
        migrations.AddField(
            model_name='barcodesummary',
            name='result',
            field=models.BooleanField(default=False, verbose_name='处理状态'),
        ),
        migrations.AddField(
            model_name='barcodesummary',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='使用人'),
        ),
    ]
