# Generated by Django 5.2.8 on 2025-11-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_code', '0002_barcodesummary_actual_time_barcodesummary_asset_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodesummary',
            name='asset_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='资产类型'),
        ),
    ]
