# Generated by Django 5.2.8 on 2025-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_code', '0003_alter_barcodesummary_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcodesummary',
            name='actual_time',
        ),
        migrations.AddField(
            model_name='barcodesummary',
            name='result_remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='处理结果备注'),
        ),
    ]
